### ISSUE TITLE
switching rotation system

### ISSUE THREAD

**Issue by pauliyobo** [luciasoftware/lucia#1]
The current rotation system that we are using works in a different way than usual.
Instead of using conventional facing directions such as north at 0 degrees and east at 90 degrees, we're using a system which currently has east at 0 degrees and north at 90 degrees
This system however, seem to have created some conflicts between the audio backends we're using, bass, and OpenAL. Therefore a switch to the conventional rotation system is required.
In addition a proper handling of the coordinate system to switch between left handed coordinate system and right handed coordinate system is required to effectively work with the audio backends.

**Comment by NicklasMCHD** [comment]
Reopening this issue because the part about fixing the z-axis isn't fixed quitte yet.

**Comment by NicklasMCHD** [comment]
Elevating this to a critical bug, because it could prevent some if not most users from using lucia.

**Comment by Alanjdv** [comment]
Is someone working on it? I would consider using pygame.math.Vector3 class for vector handling, this class has its own rotation sistem.
I could help with that if needed, though Python is not my best language I think I can code something that works and then the community could improve it.

Some considerations>
If I am right, most game engines define>
north as v0.0.-1;
south as v0.0.1;
east as v-1.0.0;
west as v1.0.0;
up v0.1.0
and down as v0.-1.0.

What are the intentions for lucia?

**Comment by Alanjdv** [comment]
I modified an example to demonstrate how it could work (code included below... if I understand how to markdown this).
I used the pygame.math.Vector3 class and its build in rotation method to illustrate the point.
It's fully compatible with lucia right now, the only problem is that the pool.update_listener_3d doesn't work properly because in the demo 90 degrees to the left or right are interpreted like the same angle.
Maybe pool.update_listener_3d should be updated to allow a second Vector3 parameter giving the facing direction, I think game engines usually work like that.

This example could be a bassis for a new rotation.py file from scratch easyly.

Including a game_object class like the one included on this demo could be interesting for simple representation of all physical objects: position, direction etc.

Hope it helps.
```
# note> This example needs an @audio.ogg@ file placed in the same directory to run.
import sys, os

sys.path.append(".")

from math import radians
import time
import lucia
import pygame

class game_object:
	'''represents a positionable object'''
	position = pygame.math.Vector3()
	direction = pygame.math.Vector3(0, 0, 1) # standard forward vector
	@property
	def forward(self):
		return self.direction
	@property
	def backward(self):
		return self.direction.rotate_y(180)
	@property
	def right(self):
		return self.direction.rotate_y(90)
	@property
	def left(self):
		return self.direction.rotate_y(-90)
	@property
	def direction_angle(self):
		return self.direction.angle_to(pygame.math.Vector3(0,0,1))

#instantiate the player
player = game_object()

lucia.initialize(audiobackend=lucia.AudioBackend.BASS)

window = lucia.show_window()

pool = lucia.audio_backend.SoundPool()

s = pool.play_3d(
	os.path.join(os.getcwd(), "audio.ogg"), 5, 5, 0, 10, 10, 0, looping=True
)

while True:
	lucia.process_events()
	if lucia.key_pressed(pygame.K_LEFT):
		player.direction = player.direction.rotate_y(-5)
	if lucia.key_pressed(pygame.K_RIGHT):
		player.direction = player.direction.rotate_y(5)
	if lucia.key_pressed(pygame.K_w):
		player.position += player.forward
	if lucia.key_pressed(pygame.K_a):
		player.position += player.left
	if lucia.key_pressed(pygame.K_s):
		player.position += player.backward
	if lucia.key_pressed(pygame.K_d):
		player.position += player.right
	if lucia.key_pressed(pygame.K_q):
		lucia.quit()
		exit()
	if lucia.key_pressed(pygame.K_c):
		lucia.output.output(
			f"Cors {round(player.position.x,0)}, {round(player.position.y,0)}, {round(player.position.z,0)}"
		)
	if lucia.key_pressed(pygame.K_x):
		lucia.output.output(f"facing {player.direction_angle}")
	pool.update_listener_3d(player.position.x, player.position.y, player.position.z, player.direction_angle)
	time.sleep(0.005)
```

**Comment by pauliyobo** [comment]
Hello.
Would it be possible for you to provide this system? I propose that temporarily we keep 2 rotation systems.

**Comment by Alanjdv** [comment]
Hey!
I am working on it. However I have some problems here... I only used git
for cloning repos before, how can I modify my own lucia branch? If I clone
lucia and modify my local copy, it is not installed on my python
distribution, how can I modify and use the local copy instead of the
release installed using the pip install lucia command?
I think I'll need to add some lines in lucia..audio.

**Comment by pauliyobo** [comment]
To be able to  contribute to the project you must do the following.
1. Fork the project
2. if you cloned the repository already go in your cloned folder and type:
git remote add myfork https://www.github.com/youraccount/lucia.git
now you will be able to push changes to your fork to which we've assigned the name myfork.
Note: make sure to stay on the development branch when making changes
git checkout development
Once you've done your changes make a commit and push it to your fork by doing the following
git push myfork development
In this way the changes will be pushed to your fork on the development branch, where new features are added.
Then you just have to open a pull request when you're done

**Comment by Alanjdv** [comment]
THANKS, very useful.
Just another question: how can I test my local modified copy of lucia? If I
create a new python program and import lucia, it will import the last
release installed. I supose I must uninstall lucia from my python distro
and install my own copy with: python setup.py from my lucia local copy,
maybe?

**Comment by pauliyobo** [comment]
python setup.py install should work fine.

**Comment by pauliyobo** [comment]
hello. Are you able to include that comment in the examples before I merge?

**Comment by Alanjdv** [comment]
Sure, Nick suggested some other changes, I am working on it and then updating.

**Comment by NicklasMCHD** [comment]
Hi.
pool.update_listener_3d(player._position.x, player._position.z, player._position.y, player.direction_angle) also breaks compatibility with existing code.

**Comment by Alanjdv** [comment]
The problema is that lucia’s current sistema uses z for the vertical axis, while PositionableObject uses y for that purpose, based on game engines like monogame and others.
That’s why in the example I passed one parameter instead of another.
How can I fix it? I added a comment explaining that in my local copy…
I cannot change the way lucia Works without breaking all the positioning sistema, the only idea I have in mind is adding a property to PositioningObject that returns a formated vector compatible with lucia’s current sistema.

**Comment by Alanjdv** [comment]
Another git newbie question:
I made a new commit today fixing some things here and there, but now I don’t know how to pull request again.
Is it the last pull request still available so you can accept it? Or I have to do anything to pull request with the new changes i commited and pushed to my repo?

**Comment by NicklasMCHD** [comment]
So. What rotational system are we going with

* The right handed one, regardless of what audio bacnkend are used (this would require in-code conversion)
* Or the coordinates system specific to the audio backend used (this would require no, or almost no in-code conversion)

I personally think, that we should go with the right handed one and do the conversion in lucia, since that would allow a developer to change audio backend mid development.

**Comment by Alanjdv** [comment]
I think the best option is the first one>
•The right handed one, regardless of what audio backend are used (this would require in-code conversion)
THe problem is that right now lucia seems to be working with another coordinates sistem.
Before implementing anything else, we need to stablish a sistem for audiobacken.
A right coordinate sistem, is I am right goes as follows:
X positive = right
Y positive = up
and z negative = forward.
In other words:
north = v0.0.-1 (nothe that z is negative)
south = v0.0.1
east = v1.0.0
west = v-1.0.0
up = v0.1.0
and down = v-1,0,0.

Then, methods like SoundPool.update_listener_3d should be rewriten.
My suggestion are:
use pygame.Vector3 class for any vector or point representation  in lucia,
make it all compatible with the right handed coordinates sistem,
and finally code wrapers for each available sound sistem: bass, openal or whatever.
The user always is using the same lucia sistem regardless the audio engine, and methods like update_listener_3d should determine what audio engine is in use, processes the data and calls the specific audiobackend methods.
But... where to start?
I could help if someone could deffine my tasks, however, I don't know how Bass or openal works, who is working on each feature...

**Comment by ultrasound1372** [comment]
What you just described is the left handed system.

**Comment by ultrasound1372** [comment]
Right now we're either going with the right handed system, x positive = right, z positive = forward, y positive = up, or the traditional cartesian system that bgt devs are used to, x positive = right, y positive = forward, z positive = up. Whichever one we choose the conversions between the two will be very simple for the end developer to grasp, just flip the y and z values if you're used to one system. Also thanks for the note about the pygame vectors.

**Comment by Alanjdv** [comment]
hmm, are you sure? I read sources like:
https://www.evl.uic.edu/ralph/508S98/coordinates.html
where they define the sistem as:
x positive right, y positive up and z negative forward, like all the
engines I worked with...
In any case is not important, we only need a doc explaining what sistem you
want and all developers can follow the guidelines.

**Comment by NicklasMCHD** [comment]
I most agree with @Alanjdv here.
The right handed is the one, where negative z is forward and positive z is backwards.

**Comment by NicklasMCHD** [comment]
Either way, I think we are going with the right handed one

**Comment by Alanjdv** [comment]
Someone, the community, or who created lucia in the first place, would need
to define goals and asign tasks. Or discuss new ideas somewhere.
I think that, internally, lucia should work with the righthanded coordinate
system, it's a standard for game engines and we can use a lot of features
from pygame with no efford. Then, we could create a variable in lucia like
lucia..coordinatesystem defining the system used, righthanded by default,
and implement an alternative bgt system alike. That is, internally
everything works with the righthanded system, but setting
lucia.coordinatesystem to bgtmode allows the user to use vectors like in
bgt and get compatible results.
In my opinion, it requires a lot of extra work and testing, but if you
really want to make it compatible with bgt stile of vectors it's the best
way.
In any case, if I am going to start coding it I'd need confirmation, who,
if anyone is going to help me, a general roadmap for bass, openal and other
features that could interact with the positioning system...
Any

**Comment by NicklasMCHD** [comment]
I think @kianoosh-shakeri  fixed this in the latest commit to master.
